# -*- coding: utf-8 -*-
"""ExpSai1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pA71JsIYsjJroRQKksXfgejrcADM98Tw
"""

#!/usr/bin/python
import sklearn

# function defenition 
def strMethod():
  "this is first line of a function, which is a comment"
  
  str = 'Hello World!'  
  print ("Original String : " + str)          # Prints complete string
  print (str[0])       # Prints first character of the string
  print (str[2:5])     # Prints characters starting from 3rd to 5th
  print (str[2:])      # Prints string starting from 3rd character
  print (str * 2)      # Prints string two times
  print (str + "TEST") # Prints concatenated string
  
  return;


# function defenition 
def conditionMethod(t1, a, b):
  "this is first line of a function, which is a comment"
  
  val = 0;
  if t1 == "ADD":    
    val = a + b
  elif t1 == "SUB":    
    val = a - b
  elif t1 == "DIV":    
    val = a / b
  elif t1 == "MOD":    
    val = a % b
    
  print (val)
  return;

####################################################
# Main Body, which is calling methods/functions
####################################################
name = 'Sai'; job = 'Sr manager'
title = "{} the {}".format(name, job); title

t1 = input("\nEnter action type ") 
conditionMethod(t1, 5, 6)

strMethod()